---
- hosts: k8s-master
  user: ansadmin
  tasks:
  - name: Initiate ansible playbook to create docker image
    copy: src=/home/ansadmin/jenkins/workspace/job121/webapp.war dest=/opt/k8s/webapp.war
  - name: Execute the ansible playbook
    command: ansible-playbook /opt/k8s/create-simple-devops-image.yml
