---
- hosts: k8s-master

  tasks:
  - name: Initiate ansible playbook to create docker image
     copy:
	src: /home/ansadmin/jenkins/workspace/job121/webapp.war 
	dest: /opt/k8s/create-simple-devops-image.yml
     command: ansible-playbook /opt/k8s/create-simple-devops-image.yml
